version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url_shortener
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - url_network

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:root@db:5432/url_shortener
    ports:
      - "8080:8080"
    networks:
      - url_network
    command: ["./build/test_task", "0.0.0.0", "8080"]

networks:
  url_network:
    driver: bridge